services:
  db:
    image: bitnami/postgresql:15
    restart: always
    container_name: postgres_db
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=Info@1234
    ports:
      - '5432:5432'
    volumes:
      - .docker/postgres:/bitnami/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
    driver: local
