services:
  db:
    image: postgres:13
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Info@1234
      POSTGRES_DB: physical_store
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_app
    restart: always
    environment:
      NODE_ENV: prod
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: physical_store
      DB_USER: postgres
      DB_PASS: Info@1234
      GOOGLE_API_KEY: AIzaSyDtf6bQuIOjc7FyL7Po7FE2theHV-3SJj0
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/app
    command: ["yarn", "start:prod"]

volumes:
  db_data:
    driver: local
